### ISSUE TITLE
unknown websocket issues

### ISSUE THREAD

**Issue by acocalypso** [Kneckter/DiscordRoleBot#1]
Hello,

I'm using your bot for quite a while now without problems, but I had to move to a new server and now the following problem occurs everytime I sent a command from discord.

```
[10.3.2020, 09:31:35]-- DISCORD ROLE BOT IS READY --
[10.3.2020, 09:31:46]Uncaught exception: {}
[10.3.2020, 09:31:46]Unexpected error, bot stopping, likely websocket

```

As I get an empty uncaught execption I can't provide any further information :(
Any Idea what might causes that issue?

Regards
Aco

Edit: I had some time to debug the script:

let AdminR=g.roles.find(role => role.name === config.adminRoleName); is calling the error

as "g.roles.find is not a function"

Edit2:
roles.find is no longer supported by name in newer versions of discord.js
I installed discord.js 11.3+ and its working again

**Comment by Kneckter** [comment]
Thanks for solving your own problem haha. I'll leave this open for now and possibly update the script so it can support the new discord.js version

**Comment by acocalypso** [comment]
I just wanted to thank you for your bot and wanted to let you know that I ported your bot to erisjs with sqlite3 which is now future proof

https://github.com/acocalypso/DiscordRoleManager

**Comment by Kneckter** [comment]
I updated the bot for Node 12 and Discord 12 (also sqlite3) so it should be good for a while. You can port any of the other changes if you like. There's a new message delete function/schedule and I changed the handling of temp roles so it doesn't delete from the DB if it cannot delete from Discord. I'll be closing this issue since it's updated but open a new one if you do use the updated bot and something breaks.
