### ISSUE TITLE
Version Discord.js outdated soon

### ISSUE THREAD

**Issue by Pogodenhelder** [Kneckter/DiscordRoleBot#17]
As far as i know, in package.json the discord version 12.4.1 is soon be outdated.
And we need to update to node 16.x with discord version 13.x

i might be incorrect but thats what i saw on poracle discord server.
So not a bug, but more a heads up to update.

**Comment by Fabio1988** [comment]
Yes you are right, this repo needs an Update, instead it's not usable anymore I think :(

@kneckter

**Comment by jfberry** [comment]
Discord has just (a few days ago) put off the retirement of APIv7 (which is what discord.js 11 and 12 use).
So there is a little more time, but adopting discord.js 13 (and therefore node 16) is now needed before Jan 2023.

Is this a popular bot? I may be able to assist with the upgrade if there are tricky bits as I have worked through most things with poracle by now

**Comment by Kneckter** [comment]
I've left this issue open because the plan is to update to Discord.js v13 and Node 16. The bot worked fine with Node 16 but my test system did not, so I rolled it back. That's mainly be the delay in updating for me.

Edit: If you have a good way to do a full system update of Node, let me know. I'm not looking to use the 3rd party node managers though. The last update I did just made PoracleJS output scrambled forms of the word "testing". No internet help on that one.
